title: Orlein
description:  Web Developer from Seoul, KOREA
author: Orlein
logo: https://avatars2.githubusercontent.com/u/11387965?s=460&v=4
github: https://github.com/orlein
about: Web Developer from Seoul, KOREA

baseurl: "https://orlein.github.io"
url: "https://orlein.github.io"

allowsearch: true

disqus_shortname: orlein-github-io
google_analytics: UA-78625712-2
google_ad_client: true
share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-sitemap, jekyll-seo-tag, jekyll-feed, jekyll-paginate, jekyll-gist]
plugins: 
  - jekyll-seo-tag
comments: true