title: Orlein
description:  C#.NET / Web Developer from Seoul, KOREA
author: Orlein
logo: 
github: https://github.com/orlein
about: Freelance developer

baseurl: "https://orlein.github.io"
url: "https://orlein.github.io"

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-78625712-2
google_ad_client: true
share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
